# Generated by Django 4.0 on 2026-02-06 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('address_line_one', models.CharField(max_length=254)),
                ('address_line_two', models.CharField(blank=True, max_length=254, null=True)),
                ('town_or_city', models.CharField(max_length=64)),
                ('county', models.CharField(max_length=32)),
                ('postcode', models.CharField(max_length=8)),
                ('default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
