services:
  web:
    build: 
      context: .
      target: prod
    container_name: cheese-beer-web
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true