# Generated by Django 5.0.2 on 2024-03-27 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=254)),
                ('email', models.CharField(max_length=254)),
                ('address_line_one', models.CharField(max_length=254)),
                ('address_line_two', models.CharField(max_length=254)),
                ('town_or_city', models.CharField(max_length=64)),
                ('county', models.CharField(max_length=32)),
                ('postcode', models.CharField(max_length=8)),
                ('default', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
