# Generated by Django 5.0.2 on 2024-03-28 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_remove_addresses_email_alter_addresses_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Addresses',
        ),
    ]
