# Generated by Django 5.0.2 on 2024-04-14 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_alter_order_stripe_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='other_costs',
        ),
    ]
