# Generated by Django 5.0.2 on 2024-04-21 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
