# Generated by Django 5.0.2 on 2024-04-22 01:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_alter_contactform_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
