# Generated by Django 5.0.2 on 2024-03-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BeerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=254, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CheeseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=254, null=True)),
                ('image_alt', models.CharField(blank=True, max_length=1024, null=True)),
                ('pairs_with', models.ManyToManyField(to='products.beercategory')),
            ],
        ),
    ]
