# Generated by Django 5.0.2 on 2024-03-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheesecategory',
            name='pairs_with',
            field=models.ManyToManyField(blank=True, null=True, to='products.beercategory'),
        ),
    ]
