# Generated by Django 5.0.2 on 2024-03-17 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_cheesecategory_pairs_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheesecategory',
            name='pairs_with',
            field=models.ManyToManyField(blank=True, related_name='cheese', to='products.beercategory'),
        ),
    ]
