# Generated by Django 5.0.2 on 2024-03-12 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_beer_category_pairs_with_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheese_category',
            name='pairs_with',
        ),
    ]
