# Generated by Django 5.0.2 on 2024-03-12 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_cheese_category_pairs_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheese_category',
            name='pairs_with',
            field=models.ManyToManyField(blank=True, to='products.beer_category'),
        ),
    ]
