# Generated by Django 5.0.2 on 2024-03-12 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_cheese_category_pairs_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer_category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='cheese_category',
            name='image_alt',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
