# Generated by Django 5.0.2 on 2024-03-12 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_beer_category_image_alt_cheese_category_image_alt'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beer_category',
            new_name='BeerCategory',
        ),
        migrations.RenameModel(
            old_name='cheese_category',
            new_name='CheeseCategory',
        ),
    ]
