# Generated by Django 5.0.2 on 2024-03-19 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_product_alcohol_content_alter_product_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_per_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True),
        ),
    ]
