# Generated by Django 5.0.2 on 2024-03-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_product_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_number',
            field=models.CharField(max_length=254),
        ),
    ]
