# Generated by Django 5.0.2 on 2024-03-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_product_product_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='displayed',
            field=models.BooleanField(default=True),
        ),
    ]
