# Generated by Django 5.0.2 on 2024-04-10 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_product_displayed'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='texture',
            field=models.CharField(default='soft', max_length=254),
            preserve_default=False,
        ),
    ]
