# Generated by Django 5.0.2 on 2024-04-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_product_units_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='texture',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
