# Generated by Django 5.0.2 on 2024-04-21 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_texture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='on_wishlist',
            field=models.BooleanField(default=False),
        ),
    ]
