# Generated by Django 5.0.2 on 2024-04-21 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_on_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='on_wishlist',
        ),
    ]
